### ISSUE TITLE
Low accuracy of date uniform

### ISSUE THREAD

**Issue by Omnificator** [markusfisch/ShaderEditor#100]
When I worked on clock shader I've figured out that "time" field of vec4 date has too low precision. It seems that many cheap android devices GPUs use float16 (half-precision) everywhere. I suggest it would be better to have hours, minutes, and seconds separately, maybe with fractional parts.
Here is my shader, it shows correct time only few hours after midnight.
```
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform vec2 resolution;
uniform vec4 date;

const float pi = 3.1415926535897932;
const float twopi = 2.0 * pi;
const float cos30deg = sqrt(3.0) / 2.0;

float knob(vec2 c) {
  return max(0.0, 1.0 - 1600.0 * (c.x*c.x + c.y*c.y));
}

float hand(vec2 uv, float period, float invthick, float invlen) {
  float angle = fract(date.w / period) * twopi;
  float s = sin(angle);
  float c = cos(angle);
  float transv = dot(uv, vec2(c, -s)) * invthick;
  float longit = dot(uv, vec2(s, c)) * invlen - 0.6;
  return max(0.0, 1.0 - transv * transv) * clamp(10.0 - 10.0 * longit * longit, 0.0, 1.0);
}

void main(void) {
  float minsize = min(resolution.x, resolution.y);
  vec2 scrcoords = (gl_FragCoord.xy - resolution * 0.5) / minsize;
  float sqdist = scrcoords.x*scrcoords.x + scrcoords.y*scrcoords.y;
  float clock;
  if (sqdist < 0.18) {
    clock = hand(scrcoords, 43200.0, 60.0, 6.0) +
      hand(scrcoords, 3600.0, 90.0, 5.0) +
      hand(scrcoords, 60.0, 120.0, 4.0);
    if (sqdist > 0.14) {
      vec2 cabs = abs(scrcoords);
      vec2 cfolded = vec2(max(cabs.x, cabs.y), min(cabs.x, cabs.y));
      float largedot = knob(cfolded - vec2(0.4, 0.0)) +
        knob(cfolded - vec2(0.4 * cos30deg, 0.2));
      float ringdist = sqdist - 0.16;
      float ring = max(0.0, 1.0 - 6400.0 * ringdist * ringdist);
      float sector = max(0.0, cos(atan(cfolded.y / cfolded.x) * 60.0));
      float smalldot = ring * sector * sector;
      float face = max(largedot, smalldot);
      clock += face;
    }
  } else {
    clock = 0.0;
  }
  gl_FragColor = vec4(vec3(sqrt(clock)), 1.0); // a kind of gamma correction
}
```

**Comment by markusfisch** [comment]
That's a nice shader! 👍 What a pity it doesn't work correctly on your device 😬 Just out of curiosity I ran it on some of my devices and it seemed to work everywhere quite well - but of course you're right.

How about a `uniform vec3 daytime;` that holds hours, minutes and seconds?

**Comment by Omnificator** [comment]
> That's a nice shader! +1 What a pity it doesn't work correctly on your device grimacing Just out of curiosity I ran it on some of my devices and it seemed to work everywhere quite well - but of course you're right.
> 
> How about a `uniform vec3 daytime;` that holds hours, minutes and seconds?

The app definitely needs a kind of shaders catalogue :wink: That [half-precision](https://en.wikipedia.org/wiki/Half-precision_floating-point_format) issue is actual at least for my old Doogee phone with MTK6582 CPU and Mali-400 MP GPU, and friend's Huawei tablet. So I think a vector of hours, minutes, seconds and subsecond might be a good solution.

**Comment by markusfisch** [comment]
There's now a `vec3 daytime` uniform: https://github.com/markusfisch/ShaderEditor/commit/2a30309e224ef9a206cd3b911e544b1d126ec0b6

It's just a `vec3` because the subseconds are already available in the `ftime` and `time` uniforms.

I just uploaded version 2.21.0 in beta, which should become available within the next few hours. You can become a beta tester here (don't worry, you can always go back to the production version):
https://play.google.com/store/apps/details?id=de.markusfisch.android.shadereditor

Alternatively you may install the app directly from GitHub here:
https://github.com/markusfisch/ShaderEditor/releases/tag/2.21.0

**Comment by Omnificator** [comment]
Great, it works as expected
