### ISSUE TITLE
Add touchStart variable

### ISSUE THREAD

**Issue by RenaKunisaki** [markusfisch/ShaderEditor#114]
This would be vec2 with the coordinates that we first started touching. That way we can do things like dragging an image around by comparing current touch position to start position.

**Comment by markusfisch** [comment]
Sounds like a good idea! Implemented in https://github.com/markusfisch/ShaderEditor/commit/bfe33e17870a92dcd2ae63027dcb2f3a083e07ca

I just released 2.24.0 which should become available within the next few hours on Google Play. If you like, you can update directly from GitHub here:
https://github.com/markusfisch/ShaderEditor/releases/tag/2.24.0
