### ISSUE TITLE
offset not changing

### ISSUE THREAD

**Issue by derheimel** [markusfisch/ShaderEditor#115]
I have a Galaxy S20FE with Android 12 and Kernel 4.19.113-23739069

As the title suggests the offset uniform does not change at all when using the shader as a wallpaper and swiping between screens.
It does have an initial value though.

**Comment by markusfisch** [comment]
Sorry, I'm afraid the home screen launcher on your device isn't sharing the offset somehow 😬 

Do you use the default launcher?

**Comment by derheimel** [comment]
Yeah that was the problem, I used the default Launcher from Samsung (One UI Home) but when I switch to Nova Launcher it works. Thanks!
