### ISSUE TITLE
More details about uniform startRandom

### ISSUE THREAD

**Issue by rorySomething** [markusfisch/ShaderEditor#118]
Excellent creation.

I'd like more details about startRandom in the FAQ or app.

It took me a while poking around on github to find it's initialized by java's Math.random in shaderRenderer.java.
Math.random gives 0.0 <= x < 1.0?

Maybe just a quick edit to strings.xml.

"Random value initialized at load ranging [0,1)."

In hindsight it feels like the 0 to 1 range should've been obvious.

**Comment by markusfisch** [comment]
Good point! 👍 The range should definitely be mentioned, and now it is: https://github.com/markusfisch/ShaderEditor/commit/46e62e3bebe4cb243acfa37397a22c5fd20e9b2c

Thanks for pointing my attention to this. It's all too easy to miss these little details that can save so much time. Sorry for not making it clear from the start 😬
