### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Frez-M** [markusfisch/ShaderEditor#13]
For some reason my phone renders only first frame, then on next frames shows only black screen. I'm not using this app for while now only because of this issue. (phone: motorola moto g 1st gen; android 5.0.2)

**Comment by markusfisch** [comment]
Very strange. Never had that issue.

I will try to get my hands on a 1st gen Moto G to investigate that. Right now, I've no idea what may cause this unfortunately.

Sorry for the inconvenience and thanks for reporting.

**Comment by Frez-M** [comment]
No problem, your app is fantastic and entertaining, as I can't do anything in it now, i'm doing my other stuff and I'm patiently waiting for new update!

**Comment by rafaellago** [comment]
I know it's not the same phone, and lots of things must have changed since then. I got a Moto G3 from work, and the app is running as fine as on my Xperia Z3 Compact. Maybe the last update Markus Relased fixed your issue?

**Comment by Frez-M** [comment]
Unfortunately, it didn't. But recently I got another phone, in which I can continue to use the app.

**Comment by Frez-M** [comment]
Today's update (24.12.'15) fixed the issue, and now the app renders normally on my Motorola Moto G 1st gen.

**Comment by markusfisch** [comment]
Good to know! Thanks for reporting.
