### ISSUE TITLE
Parser error with auxiliary whitespace characters between keywords and other tokens.

### ISSUE THREAD

**Issue by Kwauhn** [markusfisch/ShaderEditor#134]
I'll start by defining "normal" whitespaces as...
- Space (U+0020)
- Tab (U+0009)
- Line Break (U+000A)

and "auxiliary" whitespaces as all other whitespace characters.

I tried pasting code from the Github Mobile code viewer and found that it confused the parser. It turns out that the Github Mobile code viewer uses No-Break Space (U+00A0) in place of the normal space character, which works fine _most of the time_ in the editor. However, the parser does not recognize this character or any of its auxiliary counterparts when it's between a keyword and another token, i.e. `float[auxiliary whitespace]f`. This can make pasting code that contains auxiliary whitespaces quite tedious, as you have to go through and manually replace every auxillary whitespace with a normal one.

Here's an example:

I paste code...
![20230221_170453.jpg](https://user-images.githubusercontent.com/6718566/220506001-168d3f1f-4585-47d4-a6ff-6a1ed6eb812e.jpg)
... and get `'(' : Syntax error: syntax error`.

I replace the whitespaces underlined in yellow...
![20230221_170744.jpg](https://user-images.githubusercontent.com/6718566/220507034-0c18a821-3828-493a-8096-dca61d617bf9.jpg)
... and get `'returna' : undeclared identifier`.

Replacing the last whitespace underlined in yellow fixes the issue.
![20230221_170817.jpg](https://user-images.githubusercontent.com/6718566/220507470-6209831e-074e-4ac0-9259-3d5216720594.jpg)

Thanks for reading, Markus, and I appreciate your continued dedication to improving this free app.

**Comment by markusfisch** [comment]
Ah, good catch! 👍 Thanks for reporting!

I replace the No-Break Space (U+00A0) with simple spaces now (see 3638975169c579c94683d1f4eb8f1df568ad8494). Hopefully this fixes the issue.

A new version, 2.58.3, will become available on Google Play within the next few hours. You can also get it directly from Github here:
https://github.com/markusfisch/ShaderEditor/releases/tag/2.28.3
