### ISSUE TITLE
Pasting causes editor to scroll up to the top

### ISSUE THREAD

**Issue by fekga** [markusfisch/ShaderEditor#135]
As title says, whenever I paste a text, it scrolls to the top, also it loses highlighting for a short time. It seems like it pastes the full code again and that causes the scroll. I'm using the latest beta.

**Comment by markusfisch** [comment]
Ah, this was a bug 🙈 Thanks for reporting! 👍 

Fixed in https://github.com/markusfisch/ShaderEditor/commit/7ab3c360df95d40ba321294d34c38860d359cc65

A new version will be available soon.
