### ISSUE TITLE
Features request: Notification detector 

### ISSUE THREAD

**Issue by Saylion** [markusfisch/ShaderEditor#136]
I guest if this feature appear on this apps, more interactive shader will be amazing

**Comment by zedpoirier** [comment]
Agreed! Even just a simple notification count / binary state would be awesome.

**Comment by AntonPieper** [comment]
What do you mean by notification detection / counting? Whose notifications should be tracked? Do you have an example use case? It is possible to listen to notifications using [NotificationListenerService](https://developer.android.com/reference/android/service/notification/NotificationListenerService.html), though what kind of data would a shader benefit from? Note that string information like the package name etc. cannot be passed to a shader.

**Comment by zedpoirier** [comment]
My use case would be a very simple "do i have notifications" query. I like making custom wallpapers that display data like battery life, clock time, etc in visually interesting and artistic ways.

Ideally i just want to be able to have the wallpaper look/behave differently if i have a notification or not.

**Comment by AntonPieper** [comment]
I might look into this on Saturday, this sounds easy enough to integrate (famous last words). maybe a `uniform int notificationCount` and `uniform float lastNotificationTime`? I am open for feedback :)

**Comment by zedpoirier** [comment]
NotificationCount is exactly what i would need! Imagine your wallpaper getting more glitchy / intense the more notifications you have :D

**Comment by AntonPieper** [comment]
I have got it working now, will create the pull request tomorrow. Still have to figure out how to create the alert dialog before the settings open to guide the user though
