### ISSUE TITLE
QoL: Search bar in Add uniform/texture

### ISSUE THREAD

**Issue by Martysh12** [markusfisch/ShaderEditor#143]
## Problem
Reading a large list of uniforms one-by-one is tedious.

## Solution
Add a search bar to search for uniforms easily.

**Comment by markusfisch** [comment]
Good idea! Will add this as soon as I find enough time.

**Comment by Martysh12** [comment]
@markusfisch, I opened a Pull Request that should fix this issue, please take a look!
