### ISSUE TITLE
Slow shaders

### ISSUE THREAD

**Issue by ruigil** [markusfisch/ShaderEditor#16]
Hello.

Thanks for this app. I'm having too much fun with it. 

I notice that when I make a "heavy" shader with low fps, the UI slows down to a point of become unusable. Shouldn't the rendering side be separated of the UI side, option menu, spinner etc ? I mean, is there a way to play with low fps shaders and still have an usable UI ? 

Thanks

**Comment by markusfisch** [comment]
Thanks for using the app!

Well, actually rendering is already decoupled from the UI thread and runs in a separate thread. Unfortunately that doesn't mean, a slow rendering thread wouldn't affect the system of course. Long story short, there's no easy way around this.

Except, I could implement some kind of control to decrease the rendering resolution.

**Comment by ruigil** [comment]
Thanks for the reply.

If I understand what you say, the solution would be the same kind of technique that glslsandbox uses with the 2,4,8 resolution. That would be a nice thing to have. I can see that helping.

**Comment by markusfisch** [comment]
Version 2.1.0 supports multiple render resolutions.

Submitted and should be available soon.
