### ISSUE TITLE
Variable for dark/night mode

### ISSUE THREAD

**Issue by sibbl** [markusfisch/ShaderEditor#164]
I'm wondering if it's possible to check if the dark and/or night mode is enabled.

I'd like to make the live wallpaper darker when the system is set to dark mode for example.

**Comment by markusfisch** [comment]
Yes, this is absolutely possible! Good idea! 👍 

Will come with the next version which should be out soon.

**Comment by markusfisch** [comment]
Ah, sorry, I somehow totally forgot that I already [implemented this](https://github.com/markusfisch/ShaderEditor/commit/ee6738bdde4b5d3cad6c226d9734525a969774ce) 🙈😂  

Please have a look at the uniforms (tap on the three dots in the upper right and choose "Add uniform/texture"). There you will find a `nightMode` uniform, which is 1 if the device is in night mode and 0 when it's not.
