### ISSUE TITLE
L0002: Undeclared variable 'iTime'

### ISSUE THREAD

**Issue by vavavr00m** [markusfisch/ShaderEditor#166]
Examples:
https://www.shadertoy.com/view/cl3XRX
https://www.shadertoy.com/view/mtyGWy

**Comment by markusfisch** [comment]
In ShaderEditor, `iTime` is just `time`. Please check the available uniforms in the menu. Press the three dots in the upper right corner and tap on "Add uniform/texture".

Also, `time` is used in the Default shader already.
