### ISSUE TITLE
Date and daytime did not update

### ISSUE THREAD

**Issue by DinhQuocTrung** [markusfisch/ShaderEditor#171]
Date and uniform in my device did not work, they did not change.
Do you have any ideas about this?
Thank you.

**Comment by markusfisch** [comment]
Hm, this is really strange 🤔 `dayTime` is set directly from `Calendar` [here](https://github.com/markusfisch/ShaderEditor/blob/master/app/src/main/java/de/markusfisch/android/shadereditor/opengl/ShaderRenderer.java#L505). I don't see how this can go wrong, unfortunately.

Would you mind running a debug build, and checking logcat, to see what's going on?

**Comment by DinhQuocTrung** [comment]
There are several error in my device settings about time and I fixed it.
Thank you, it worked.

**Comment by markusfisch** [comment]
Happy it's working now! 😄
