### ISSUE TITLE
(Question) Linear sampling for backbuffer

### ISSUE THREAD

**Issue by ajboots** [markusfisch/ShaderEditor#174]
Hello. I am here from shadertoy to make my favorite shader into my phone background!

Shadertoy automatically adds interpolation to my texture samples allowing for a smooth transition frame to frame.

Using the sampler2D, I am getting sharp transitions in direction (snapping from SW to SS to SE).

How could I tell my texture to interpolate the sample with nearby pixels instead of getting the one nearest to my request? 

Sorry in advance if there was a better place to post this.

**Comment by ajboots** [comment]
**i found out how to do it by using the in app add for uniform**

**Comment by markusfisch** [comment]
Sorry, this function is really quite a bit hidden 🙈  Anyway, happy you found it! 👍
