### ISSUE TITLE
Suggestion: Add typing-relevant bar above keyboard

### ISSUE THREAD

**Issue by AntonPieper** [markusfisch/ShaderEditor#175]
I thought, maybe adding a bar above the keyboard for some actions (like auto complete) could be useful. The thing is, I also like simplicity and a simple user interface. So I am asking if this is a wanted feature?

Here is a quick sketch (of course this is not the design I would implement)
![Screenshot_20240417-172914](https://github.com/markusfisch/ShaderEditor/assets/94118572/a152c00c-06d5-4085-84bc-d72c0f930788)

**Comment by markusfisch** [comment]
This could be a really nice feature that could potentially greatly enhance the editing experience, I think.

I didn't really explore this because most keyboards already have a shortcut bar (like in the screenshot), and I thought another one could probably be too much. But looking at your mock-up, it might work out! 🤔 

Another thing to consider is that another bar over the keyboard would decrease the editor in landscape mode even further, maybe to just one line. Of course, editing in landscape has always been a bit problematic so maybe a simple solution would be to just show this bar when there's enough vertical space.

**Comment by AntonPieper** [comment]
In landscape mode, one can currently use floating keyboards (at least GBoard supports it), problem being that custom in-app bars can't track the keyboard afaik. If you are using landscape mode though, the distance to the tab-key at the top is less anyway though so it might not be problem.
![Screenshot_20240418-180931](https://github.com/markusfisch/ShaderEditor/assets/94118572/6cca4062-b375-4f48-989c-2627de22e499)

You are right that most keyboard apps already have an auto complete-bar (which is useful in most cases, but maybe not in a code editor), which sadly takes away space. I thought, maybe one could hijack it, but I haven't found anything about that yet😢.

There also seems to be some way to tell the keyboard-app to not show suggestions _without_ showing the password field, as Termux does this (but I also haven't found out how they do this yet):
![Screenshot_20240418-181806](https://github.com/markusfisch/ShaderEditor/assets/94118572/12b05426-d7a3-477e-aa9c-79a4fc60f894)

**Comment by markusfisch** [comment]
> In landscape mode, one can currently use floating keyboards…

Well, yes, if the screen is big enough 😉 I figure that typing this way is probably really unpleasant 🤔 But yes, this is a solution, and I can't see a better way anyway.

> …I thought, maybe one could hijack it, but I haven't found anything about that yet😢.

I thought the same but haven't found a way to this either.

> There also seems to be some way to tell the keyboard-app to not show suggestions without showing the password field, as Termux does this…

And Termux is a really good example for that extra bar over the keyboard! I really like how it's working there.

> Edit: In Termux, it might have something to do with [these overridden methods](https://github.com/termux/termux-app/blob/2f40df91e54662190befe3b981595209944348e8/terminal-view/src/main/java/com/termux/view/TerminalView.java#L1027-L1043)

It certainly looks like it would… 🤔
