### ISSUE TITLE
Discard is not working properly

### ISSUE THREAD

**Issue by fekga** [markusfisch/ShaderEditor#18]
According to the the OpenGL ES 1.00 specification the discard keyword will not update the buffer if called. Thus it should contain the last written pixel value in the buffer until overwritten.
In the ShaderEditor discard will cause the (not) written pixel to be black. I think this is caused by the clear command at the start of rendering. It would be nice to make use of the discard keyword!

**Comment by markusfisch** [comment]
Interesting - I'll check that and change it if possible. Something tells me dropping glClear() will have side effects but I'll try.

**Comment by markusfisch** [comment]
Dropped glClear() in https://github.com/markusfisch/ShaderEditor/commit/bba8c4e75b6478aa60c2f6e3dc74117268a7e5d1.

Works on all of my devices without problems. Calling discard will preserve the buffer now. Will be in the next release.
