### ISSUE TITLE
[feature request] - shader list ordering

### ISSUE THREAD

**Issue by gaborfekete-greehill** [markusfisch/ShaderEditor#182]
I have over 50 shaders now and when I open the application I always have to scroll down to the latest one. It would be nice to have the latest shader at the top or even sort them by created/modified dates.

**Comment by markusfisch** [comment]
Good point! I will add in the next version!

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/ShaderEditor/commit/d0f65170faf962d8beff2a19e31f71f9c7449f36
