### ISSUE TITLE
[Bug] `PagerTabStrip` Discrepancy between Play store version and self-built version

### ISSUE THREAD

**Issue by AntonPieper** [markusfisch/ShaderEditor#185]
The `Add uniform/texture` menu seems to be rendered incorrectly in the released Play store version `2.33.3`.

If I build the app from source, the `PagerTabStrip` renders correctly, but in the Play store version there is *none at all*.
| Playstore | Source |
| - | - |
| ![Playstore Version](https://github.com/markusfisch/ShaderEditor/assets/94118572/3d45917e-3936-4cf6-be9f-31596e31882a) | ![Source Version](https://github.com/markusfisch/ShaderEditor/assets/94118572/7d5fede7-38bf-4d34-be14-1df0c08dd57e) |

**Comment by markusfisch** [comment]
Good catch! 👍 I somehow didn't notice the strip vanishing 🙈 

Fixed in https://github.com/markusfisch/ShaderEditor/commit/267d24a9d468ba2e307215c131cd5174074cd417
