### ISSUE TITLE
Issue: Reviewing the approach of `inputType=textVisiblePassword` & Proposing to optionalize it

### ISSUE THREAD

**Issue by StaticReasons** [markusfisch/ShaderEditor#188]
> This section is about the story of how I have trouble with this issue; For technical analysis skip this section.

Moment ago I updated Shader Editor and was surprised to see there's so much nice enhancements and evolution on this app~

However there's one thing striking my coding experience: The password-typed IM.

Idk why is it set blocked to this way --- but it troubles me a lot at this moment.
I used to code shaders with my IME in a coder-oriented-designed theme which has an extra-powerful ability to input symbols like `,.:;[]{}`, like this:

![image](https://github.com/user-attachments/assets/837ab141-70c0-460b-8f73-9bde7b11d896)

(Baidu Input, PaddlePaddle skin)

Before the updates with auto-completions I could still input symbols effectively with my IM, only need to upswipe the corresponding key.

But after upgrading to the latest version my familiar panel disappeared, being replaced bt a "Safe Input" panel which can no longer input symbols effectively like before, and I cannot even screenshot it because the system says "There's sensitive information on the screen"!

Well, you may ask "Didn't the aut-completion bar make it up and help you? " --- Unfortunately it didn't. Every time I needa input a symbol, for example, the parathesis in `vec3(1.0...`, the parathesis didn't popup as suggestion right after inputing the identifier `vec3` --- instead you need to input one extra space then the suggestion could come up after that.

`vec3 (1,0)`, hmm...... How can it be a nice code style.

**So—I hope the issue could be solve in the way of canceling the password-typed input, or at least add an option for the user to cancel it.**

---

### Analysis:

> The contributor may be more familiar than me with this... but I guess it's still better to figure out why over here.

The password-like keyboard is because the `ShaderEditor` widget, inherited from `LineNumberEditText‎` < ... < `TextView` was set an attribute `android:inputType` with the flag `textVisiblePassword`:

https://github.com/markusfisch/ShaderEditor/blob/12813c04722b9e9b152d70b53e25241cc02d7688/app/src/main/res/layout/fragment_editor.xml#L21-L39

The change was commited by @AntonPieper in commit https://github.com/markusfisch/ShaderEditor/commit/ac24b7c6f235aefb716f6e7e336999c251535aed, which is part of the feature development in PR https://github.com/markusfisch/ShaderEditor/pull/180 for this issue https://github.com/markusfisch/ShaderEditor/issues/175.

And at that time we did noticed about the password-typed keyboard issue and even find that Termux has managed to solve the problem as it hinders IM's auto completion without setting the password input type.

But idk why our code at last didn't made it.

I'll try to find possible solutions in the next comment.

**Comment by AntonPieper** [comment]
Hello, thanks for the detailed report👍.

You are right that termux solves this without using a visible password field. The `textVisiblePassword` was the first attempt at removing the auto completion bar. The real solution was to override [`getAutofillType`](https://github.com/markusfisch/ShaderEditor/blob/12813c04722b9e9b152d70b53e25241cc02d7688/app/src/main/java/de/markusfisch/android/shadereditor/widget/ShaderEditor.java#L283) and `textVisiblePassword` was a leftover. The solution is to remove the inputType attribute. I can open a PR for this tomorrow if you want

**Comment by AntonPieper** [comment]
Also, the parenthesis problem should definitely be fixed, I will look into that as well.

**Comment by StaticReasons** [comment]
No I tried it doesnt seem like to be so simple like that.
I experiemented on my phone and after removing "textVisiblePassword" field none of the following workarounds managed to disable GBoard's suggestion:
- try different flags for `inputType`, including: `none`, `text`, `textNoSuggestions`, `textFilter|...`
- set input flags programmeticly in the constructor of class `LineNumberEditText`
- complete the autofill override setup as requested in [this Android's Doc](https://developer.android.com/identity/autofill/autofill-optimize#custom), like the following:
```java
	/**
	 * Define functions required for AutoFill API
	 */
	@RequiresApi(api = Build.VERSION_CODES.O)
	@Override
	public int getAutofillType() {
		return AUTOFILL_TYPE_NONE;
	}

	@RequiresApi(api = Build.VERSION_CODES.O)
	@Override
	public void autofill(@NonNull SparseArray<AutofillValue> values) {
		// Do nothing
	}

	@RequiresApi(api = Build.VERSION_CODES.O)
	@Override
	public AutofillValue getAutofillValue() {
		// does nothing
		return null;
	}
```
- Seek solutions in this ancient issue: https://issuetracker.google.com/issues/36934423, and change the class `LineNumberEditText` inherited to be `AutoCompleteTextView`, `EditText`, and their AppCompatible variations.

Also the magic in Termux is probably not completely revealed:

https://github.com/termux/termux-app/blob/57e4ef456b9ad154eccc4b049e21513f1ac5ec06/app/src/main/java/com/termux/app/terminal/TermuxActivityRootView.java#L23-L63

https://github.com/termux/termux-app/blob/57e4ef456b9ad154eccc4b049e21513f1ac5ec06/terminal-view/src/main/java/com/termux/view/TerminalView.java#L269-L301
- In some settings Termux seems uses `InputConnection` rather than `EditText`.
- Termux also sets `inputType` in a trouble-dealing manner, and their code involves `InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD`, `InputType.TYPE_TEXT_VARIATION_NORMAL`, and even `InputType.TYPE_NULL` in differetn situations!

It is also noticable that though Termux succeeded to disable the suggestion, the bar is blocked by numbers and actually users can no longer access GBoard's more functions like Clipboard, Text Editing, Settings, Voice Input, and more. **To some extent, their practice is not perfect either.**

![image](https://github.com/user-attachments/assets/b3d6c89f-81f2-483f-b042-87b4a7be294a)

In some higher perspective, the whole problem may be just a shamble of misinteroperation between IMs like GBoard, Android UI coms, and maybe Autofill framework or more.

And... afterall Shader Editor is not a "popular" App. It is more or less made for monority groups, for the geeks who wanna code and explore CGs just on our own mobile phone. Maybe it is OK to pass back the autocomplete problem to users, like me geeklize my IM or just use a second IM which disabled autocomplete globally in its own option.
Or just optionalize the password inputType.

---

Idk if I missed sth in my attempts but I'm just afraid tomorow morning you'll find it tough as well and wasted hours on it with the same result like mine today. Anyway good luck

**Comment by AntonPieper** [comment]
I have tried to set the inputtype to null manually and it works on the emulator and my pixel 7 Pro. Could you test this on your device @StaticReasons? The code is at [my fork on branch "input-type"](https://github.com/AntonPieper/ShaderEditor/tree/input-type). If you don't have the time to build it yourself, I have a APK here (not signed, debug build):

**Unsigned Release APK:** [`app-release-unsigned.zip`](https://github.com/user-attachments/files/16236926/app-release-unsigned.zip)

**Comment by StaticReasons** [comment]
Omg it works! That's magical~
It works on my honor phone & huawei tablets.
![Screenshot_20240716_004814_de markusfisch android](https://github.com/user-attachments/assets/d4830e2a-50b8-4fc2-a649-4e95fa205de6)
![Screenshot_20240716_010117_de markusfisch android shadereditor](https://github.com/user-attachments/assets/e6a290cf-b2f3-4c53-a231-c9c46c16e7dd)
Well seem like it's my understanding of Android being too poor though.
Brainhacking... But anyway good job it works
btw id withdraw the saying that null mode hinders curcial things. The screenshot showed the settings was still triggerable. Maybe I'm also too unfamiliar with Gboard.

**Comment by StaticReasons** [comment]
Also this time I'm not sure if my issue title is named good enough... Still not confident in my English. Is it?
