### ISSUE TITLE
Unable to open the menu

### ISSUE THREAD

**Issue by nathanross49** [markusfisch/ShaderEditor#2]
I love this application but it has two major flaws and a minor flaw that make using it difficult. 

First, after I updated my phone to Android Lolipop I lost the ability to open the menu. I can still switch between shaders, but holding down the selector no longer opens the menu. This is not a bug in your application, but severely limits the application's usefulness in my case. I would like to see a more intuitive and universal menu activation, such as a sliding drawer from the left.

Second, the inability to disable the live preview from the text editor causes issues when editing bright, noisy, or slow shaders. I would like an option to disable live preview, please.

Finally, the text editor makes editing long lines of code difficult as touching nearby shorter lines scrolls back to the left side. I'm not sure if improving this experience is within your ability, but I thought I'd mention it away.

I wrote about my inability to open the menu in an app review, but I realized you did not check there regularly. I created this account to thank you for making this awesome app and request a few changes. Thank you.

**Comment by markusfisch** [comment]
Hi Nathan,

Thanks a lot for creating an account and filing an issue! Always good to get feedback! And sorry I missed your review on Google Play. I'll have to improve there.

The missing menu button in Lollipop is a problem indeed. Especially for devices without a hardware menu button. In theory, there should be a menu icon (three vertical dots) in the lower right corner of the screen when the keyboard isn't visible. But that's not exactly obvious nor very handy, of course. So I will definitely change that; most likely by implementing a overflow menu button in the top right corner of the title bar or something like that.

Implementing a drawer is also a very good idea. Thought about that, too. The thing is, using that component (and supporting Gingerbread) would make the app about 2 MB in size. And I'm a bit unsure if I should go that way.

The live preview can be disabled, actually, but it's a preference ("compile on change") which is only available through the menu :) However, there's a shortcut: pressing the save icon for two seconds or so toggles between compile on change and compile on save. The icon will change from an arrow pointing downward (into a tray) to a play button (over the tray). After that, you'll have to press the play button to compile the shader.

The jumping viewport when missing a long line does catch me too every once in a while. Unfortunately your guess is right - there's not much I can do about that. The best recommendation I can give you is to increase the font size a bit so lines become harder to miss. There are two ways to change font size: in the preferences (available in the menu, this really needs a fix :)) or by using a zoom (or pinch) gesture. The latter isn't as accessible as I'd wish it to be, so try it with a little care.

**Comment by nathanross49** [comment]
Thank you for the response.

On my phone the menu button on the bottom right of the screen does not show up. I'm using a Galaxy S5, which has hardware home, back, and multitasking buttons, but not a menu key.

I love the application's small file size, so I understand wanting to avoid bloating features like the drawer. I'm sure a low impact alternative is available.

What I meant by disabling the live preview was to have a solid background behind the text editor instead of running the shader. I disabled compile on change before updating my phone, though it's good to know that shortcut. I was hoping to work on slow shader code without the text editor running slowly as well.

Having the shader view run fullscreen hiding the action bar and returning to the editor with the back button would be amazing if that was possible. I accidently exited the app with the back button numerous times when I started using the app.

I can still access preferences by selecting Shader Editor's live background from my phone's change background menu and selecting settings. Sadly that does not allow me to manage shaders. I recently had to comment out an existing shader to write a new one.

I understand the limitations on text editor so I will try using larger fonts to scroll or smaller fonts to avoid scrolling.

Thank you making my favorite app and keeping in touch with the community.

**Comment by markusfisch** [comment]
About the menu, I forgot, you can also get to the menu with a long press on the shader drop down in the action bar! That should work everywhere - does it?

Okay, now I understand, of course, separating the editor from the preview is not a problem and I will going to support this with the next release.

And thank you for using Shader Editor! I really appreciate the feedback.

**Comment by nathanross49** [comment]
That is my main issue. Long pressing on the shader selector on the action bar does not open the menu on Lolipop, at least not on my S5. It worked in 4.4.4 and that's what I used to use to open the menu.

**Comment by nathanross49** [comment]
I was hoping you could add another way to open the menu that did not rely on software or hardware menu buttons or the long press feature that seems to be broken in Android Lolipop. I love this app, but not being able to create new shaders makes using it difficult.

**Comment by markusfisch** [comment]
Oh, that's bad. I was really hoping at least the long press would still work.

That makes the issue even more severe and I will definitely fix this very soon.

**Comment by nathanross49** [comment]
Thank you. I appreciate your help. Sorry for not being more clear about the issue earlier. It may be that Verizon's fork of Samsung's fork of 5.0 and my specific model of phone is causing the issue, but I am glad this is bring resolved anyway.

Thank you again. I really appreciate this.

**Comment by nathanross49** [comment]
To be more precise, holding down the shader drop down selector opens the shader drop down instead of the menu after I updated my phone's OS.

The delay between holding the drop down and the menu opening remained the same, just which menu opens is different.

This is just an issue with Lolipop and not your responsibility in any way. You are going above and beyond your responsibility as a developer in helping me with this issue and my feature requests. I want to donate to support this project, but I haven't found any links to do so.

**Comment by markusfisch** [comment]
Just pushed a fix for this to Google Play. On Lollipop, there's now a "more" icon (three vertical dots) in the action bar (a the top right) that opens the shader menu. Latest version is 1.6.2 which should become available within the next few hours.

According to my tests, the missing menu button (at the bottom right) seems to be a Samsung or Verizon issue indeed. But since the long press (on the shader) doesn't work on Lollipop anymore anyway, it's really vital to have that "more" icon I think.

As soon as I can allocate a bit more time, I will rework the user interface to be more up to date.

At the moment, I haven't setup anything to make a donation. May be I will do that over Google Play in the near future. But thanks for asking anyway.

**Comment by nathanross49** [comment]
I really like the update. I finally separated my shaders into their own shader and noticed the new battery and rotation uniforms. Thank you for fixing this issue.
