### ISSUE TITLE
Add support for the magnetic sensor

### ISSUE THREAD

**Issue by rafaellago** [markusfisch/ShaderEditor#20]
Would be nice to have the magnetic sensor of the phone exposed on the phone. Mostly because the sensor detects a lot of magnetic activity while I'm on the subway, and I'd like to use that to make more dynamic shaders. 

I don't know if there is a specific area for feature request. So I'm posting here, sorry if it is on the wrong place.

**Comment by markusfisch** [comment]
Good idea! And it's quite easy to do: I just have to add a sensor listener for [TYPE_MAGNETIC_FIELD](http://developer.android.com/reference/android/hardware/Sensor.html#TYPE_MAGNETIC_FIELD). I'll add this in the next release (the one after 2.2.0 which I just pushed to Google Play).

And you're spot-on, this is the perfect place for feature requests :)

**Comment by rafaellago** [comment]
Great to know, Thank you!

**Comment by markusfisch** [comment]
https://github.com/markusfisch/ShaderEditor/commit/c18ff8f7f282c00869b4677f6b7709fe0486dd3f exposes the magnetic sensor. Just had to try it right away :) Seems to work but I need to test it a bit more before release. Will come soon.

**Comment by rafaellago** [comment]
Works perfectly, thank you

**Comment by markusfisch** [comment]
You're welcome. Thanks for filing an issue.
