### ISSUE TITLE
Editing when an error is highlighted

### ISSUE THREAD

**Issue by gabor-zinemath** [markusfisch/ShaderEditor#21]
Since some versions now when an error occured and you try to edit, the cursor ('|' character) isn't appearing in the text, making it really difficult to resolve the error. It seems as if the red highlight color is over the editing rendering.

**Comment by markusfisch** [comment]
Weird. And I didn't notice that somehow until now, but you're right.

It seems to be a problem in Android's EditText implementation that draws the cursor before drawing the background of the Spannable. There's an [issue](https://code.google.com/p/android/issues/detail?id=172001) about that.

To deal with that, I made that red background color transparent in https://github.com/markusfisch/ShaderEditor/commit/7399fd5ca168b1b146ee7b72d3de6e397fd192b8. It's not that eye-catching anymore but probably still good enough.

Will be in the next release.
