### ISSUE TITLE
Sorry to bother, I have a question regarding OpenGL rendering. Thank you.

### ISSUE THREAD

**Issue by jane00** [markusfisch/ShaderEditor#213]
On Android, LibGDX mentions that its Live Wallpaper service and regular app mode cannot coexist in the same app due to synchronization reasons. What is the issue with LibGDX's implementation? Other applications using OpenGL don't seem to have this problem. For example, your Shader Editor can simultaneously display as a wallpaper and run the editor in windowed mode, with both interfaces rendering their own shaders or even the same shader simultaneously. Additionally, in my tests, I found that while LibGDX can technically support both modes and compile successfully, there is intermittent flickering when both the app and the live wallpaper are displayed at the same time. This flickering seems to show frames intended for one interface being rendered in the other interface. What is the technical issue causing this flickering?

**Comment by markusfisch** [comment]
Sorry, I don't know LibGDX and can't say anything about it's limitations or internals. This is more a question for LibGDX, I think.

All I can say is that it's technically very well possible to have a shader running in a WallpaperService and another in an Activity, as you already know.

**Comment by jane00** [comment]
> Sorry, I don't know LibGDX and can't say anything about it's limitations or internals. This is more a question for LibGDX, I think.
> 
> All I can say is that it's technically very well possible to have a shader running in a WallpaperService and another in an Activity, as you already know.

Thank you very much. Sorry to bother.
