### ISSUE TITLE
samplerCube 

### ISSUE THREAD

**Issue by pcornier** [markusfisch/ShaderEditor#22]
Hi, I tried to play with samplerCube and textureCube() but it seems to stop the rendering. Is it possible to use that type of samplers ? (I'd like to import shaders I made on Shadertoy)

**Comment by markusfisch** [comment]
Hi, sorry, unfortunately not. At the moment, cube textures are not supported. But I will try to add it for the next release.

I'm planning to make the app as compatible as possible to Shadertoy because I want to use their API to import shaders.

**Comment by markusfisch** [comment]
Do you have any preference/idea how you'd want to set/define the six textures for the cube? From a predefined selection (like Shadertoy) or maybe from only one source image (mapping?)? I think it'd be better if a user could create a cube texture from something.

**Comment by pcornier** [comment]
I think there is already something called a "vertical cross cube" format that can be used to group six sides of the cube into a single image. You can found examples by searching "vertical cross cube images" on google.

**Comment by markusfisch** [comment]
Okay, that's just what I thought it would be :)

I'll need to think a bit about how to implement that so that a user can create/use/compose textures in that format. Maybe I should just use it as a mask when importing a texture or something like that.

**Comment by rafaellago** [comment]
I like the way people made on shdr http://shdr.bkcore.com/ but of course, I have no idea how could this be presented on a small mobile screen.

**Comment by markusfisch** [comment]
Does shdr.bkcore.com support cube textures? Can't find anything. Or did you mean the UI in general?

**Comment by rafaellago** [comment]
Ok, I think I misinterpreted things. Thought you were saying about applying shaders to 3d objects.

**Comment by pcornier** [comment]
I think you don't have to worry about how users are going to generate their images. You can just print a grid or an unfolded cube on top of the texture preview to show which part will be used.

**Comment by markusfisch** [comment]
Yes, I think so too. I'm going to try that.

@rafaellago: that's a bit further down on the list :)

**Comment by pcornier** [comment]
Sounds good, thank you!

**Comment by rafaellago** [comment]
@markusfisch no worry, I'm quite pleased with how the app is at the moment. Maybe, camera integration, but since you are trying to make the app shadertoy compatible, I think that soon I'll see the feature.

**Comment by markusfisch** [comment]
Available in 2.4.0, here's a link to the Beta: https://play.google.com/apps/testing/de.markusfisch.android.shadereditor

**Comment by markusfisch** [comment]
Pushed 2.4.0 in production. Should be available in the next few hours.

**Comment by pcornier** [comment]
Oops too late. It works very well, thank you. However, I noticed that clicking the small insert button adds "sampler2D" instead of "samplerCube" but that's not a big issue.

**Comment by markusfisch** [comment]
Oh my :) Will fix this tomorrow. Expect a 2.4.1 very soon. Thanks for reporting!

**Comment by fekga** [comment]
Can you add some example cubemap as with the textures? Or give a link where
cubemaps compatible with the editor can be found?
Thanks!

2016-06-02 22:40 GMT+02:00 Markus Fisch <notifications@github.com>:

**Comment by markusfisch** [comment]
Yes, that would also make very much sense. I'll try to find (or create) some. Will be in 2.4.1.
