### ISSUE TITLE
Add a random uniform that changes every time the shader loads

### ISSUE THREAD

**Issue by dax105** [markusfisch/ShaderEditor#23]
Hello, I'd like to make the shader look different every time it loads. Would It be possible to add some uniform that gets randomized at the load of the shader and then stays constant? It would help me a lot, thanks!

**Comment by markusfisch** [comment]
Hi, yes, that's not a problem. I would add it for the next release.

By the way, would would adding a (calendar) date/time uniform also (or instead) be of interest to you? Then you could use this to have a (daily) unique start value, for example. I'd add something like ShaderToy's (https://www.shadertoy.com/) vec4 iDate uniform (contains year, month, day and time in seconds). The time member would update every second, of course, so it wouldn't fit your problem I think.

**Comment by dax105** [comment]
Yeah, that would be really cool as well. The more uniform options, the better, really. I was also thinking about a timeunlocked uniform (or something similar) - basically a time uniform that only increments if the device is not on the lockscreen, you could then make the wallpaper look differently on your lockscreen and make some transition after the device gets unlocked. I think that would also be a useful addition.

**Comment by markusfisch** [comment]
https://github.com/markusfisch/ShaderEditor/commit/ced177f1075a99429ea3bf210f64e30fb4a9bb18 implements the time and random (at load) uniforms.

The timeunlocked uniform you proposed is a bit more complicated unfortunately. I'm evaluating the idea.

**Comment by markusfisch** [comment]
Released in Version [2.3.1](https://play.google.com/store/apps/details?id=de.markusfisch.android.shadereditor).
