### ISSUE TITLE
Duplicate file

### ISSUE THREAD

**Issue by JFonS** [markusfisch/ShaderEditor#30]
`app/src/main/java/de/markusfisch/android/shadereditor/widget/TouchThruDrawer`**`L`**`ayout.java`

and

`app/src/main/java/de/markusfisch/android/shadereditor/widget/TouchThruDrawer`**`l`**`ayout.java`

seem to be duplicated and the program can't be compiled without removing the second one.

**Comment by markusfisch** [comment]
Apple's HFS bit me again. Sorry for that. https://github.com/markusfisch/ShaderEditor/commit/516afbb1003c658f1aba8128cb9b4495f8e71c7d removes the duplicate.
