### ISSUE TITLE
Crashing shader, uneditable

### ISSUE THREAD

**Issue by xloem** [markusfisch/ShaderEditor#32]
I foolishly had 'save on run' active on this shader which crashes the app whenever it is run, and now I can no longer even open it.

I can't even find the shader on the sdcard.  Are they stored somewhere I can access without a rooted phone?

**Comment by xloem** [comment]
Ah-ha, "run in extra activity" allows me to edit the shader without running it.

**Comment by markusfisch** [comment]
Fortunately you solved it :)

To answer the question, shaders (and their meta data) are stored in a SQLite database. Without root access, there's no way to alter it except to wipe everything out (by using delete data from app settings).
