### ISSUE TITLE
"time" uniform loses accuracy

### ISSUE THREAD

**Issue by xloem** [markusfisch/ShaderEditor#33]
As some time goes by, the "time" uniform becomes increasingly inaccurate for me.  This makes animations appear very jerky pretty quickly.

One way this could be resolved would be by providing an "animation length" in the settings, and then passing time as a fraction of that length.  For example, if "animation length" was 5 seconds, then "time" might be 0.4 after 2 seconds, and then 0.4 again after 7 seconds.

**Comment by markusfisch** [comment]
Does precision highp change anything?
https://github.com/markusfisch/ShaderEditor/issues/10#issuecomment-160463706

**Comment by xloem** [comment]
No.  The issue still arises.

Duplicate of #10.

**Comment by xloem** [comment]
Reopening because #10 is closed.

**Comment by markusfisch** [comment]
Solved in [2.4.4](https://github.com/markusfisch/ShaderEditor/releases/tag/2.4.4)
