### ISSUE TITLE
Preview keeps open

### ISSUE THREAD

**Issue by fekga** [markusfisch/ShaderEditor#35]
Since the latest update running the shader in a seperate window causes that preview window to remain open when pressing the 'back' button on my xperia z1 compact. This wasn't happening until now.

**Comment by fekga** [comment]
Forgot to mention that the FPS indicator has vanished. It may be because it counts it when the preview is finished?

**Comment by markusfisch** [comment]
Ah, yes, I see. That's because the preview activity is now started as a new task to support multi-window mode in Nougat (what shouldn't change the standard behavior of course). Will fix as soon as possible. Sorry for that and thanks for reporting.

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/ShaderEditor/commit/7291522828198da79ade493b5daf3d2bd155005d.

Published Version 2.4.5 in beta. Should become available in the next hour or so.
