### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ebraminio** [markusfisch/ShaderEditor#4]
Hi. Would you please specify the license this great and cool app is released in? I hope it would be a free one :grinning: It is needed for adding this app to F-Droid, [more info](https://gitlab.com/fdroid/fdroiddata/merge_requests/727). Thank you

**Comment by ebraminio** [comment]
[Ops](https://gitlab.com/fdroid/fdroiddata/merge_requests/727#note_1114761)!!! How I didn't see it! Thank you :-)

**Comment by markusfisch** [comment]
Yes, of course, it's the MIT license (http://opensource.org/licenses/mit-license.php). Put a comment about it at the end of README.md. Thanks for asking.

**Comment by markusfisch** [comment]
Just added it :)

**Comment by ebraminio** [comment]
Thank. Would you please tag a release also? On Github It is as simply as going to [https://github.com/markusfisch/ShaderEditor/releases/new](new release) and pressing the green button :P

**Comment by ebraminio** [comment]
Also please do the same on https://github.com/markusfisch/WaveLinesWallpaper Another very lovely app :-)

**Comment by markusfisch** [comment]
Done :)
