### ISSUE TITLE
Chromecast compatibility?

### ISSUE THREAD

**Issue by Gnurou** [markusfisch/ShaderEditor#41]
Hi,

The README states "_Live preview in background or on an extra screen_", but I suppose the extra screen is a physically connected screen?

It would be quite cool if this app had support for cast on secondary screens, so it could adapt to the native resolution of the display and output better quality than the basic Android mirroring.

Is it something you have thought about? If not, I may give it a try to see whether this is worth doing.

**Comment by markusfisch** [comment]
Ah, sorry, by screen I just meant another (Android) Activity that may or may not be on the same physical screen.

But showing a shader on a bigger screen would sure be nice! It's just that Chromecast [Receiver Apps](https://developers.google.com/cast/docs/receiver_apps) are HTML5/JavaScript so we cannot use the existing renderer there.

Now, setting up a HTML5/JavaScript renderer wouldn't be too difficult, but there are some challenges/questions. For example, what do we do with sensor data? Should we transfer sensor data from the mobile to the HTML5/JavaScript renderer on the Receiver or just ignore uniforms that do not exist on a Chromecast? And how to transfer textures?

Also, I don't really know how well (the different versions of) Chromecast GPU's perform. We should probably test that first (may be by simply loading [GLSL Sandbox](http://glslsandbox.com/) on a Chromecast - has anyone done this already?).

If you'd like to explore that possibility I'd really appreciate it!

**Comment by Gnurou** [comment]
Interesting idea - what I had in mind was more in the lines of locally rendering a buffer at the remote display's resolution, and sending that buffer to be displayed. Rendering on on the Chromecast device is an equally interesting idea, though I don't know whether these little devices have the guts to display complex shaders?

I may try to give a look at both ideas. I am mostly using your app on a Pixel C device, and it is just a breeze with the keyboard and strong GPU. My only issue is that the Pixel C's display resolution does not beam too cleanly to a remote device due to the different resolutions, hence my search for a way to improve this.

Let me close this issue for now. Thanks for the great app and thanks for making it open-source!
