### ISSUE TITLE
Renaming Shaders

### ISSUE THREAD

**Issue by stefnotch** [markusfisch/ShaderEditor#43]
A great addition would be the ability to rename shaders.
It would make it far easier to organize them.

**Comment by markusfisch** [comment]
Yes, that's on the list for a while now. Will be in the next release on Google Play.

**Comment by markusfisch** [comment]
Finally implemented in https://github.com/markusfisch/ShaderEditor/commit/4795e9fa39379d7312750c07b190c3b719675466

**Comment by demicuz** [comment]
Great! Can't wait for the next release as I'm too lazy to build it myself.
