### ISSUE TITLE
missing mod() and floor() functions

### ISSUE THREAD

**Issue by mateosss** [markusfisch/ShaderEditor#49]
Hi I hope this is not an out of place question, I don't know almost anything about shaders, but the opengl docs says there is a floor() and a mod() function, that doesn't seem to be available in the app, I suppose many others functions would be missing too.

Why is that? Is there a way to use those functions?

**Comment by markusfisch** [comment]
Hm, well, I suppose you're trying to use floor() or mod() on an integer then? Try this:

```glsl
// make sure to use a dot, not integers like 1
float f = floor(1.3);
```

Please check out the official documentation for [floor](https://www.opengl.org/sdk/docs/man4/html/floor.xhtml) and [mod](https://www.opengl.org/sdk/docs/man4/html/mod.xhtml).

The app does not change your GLSL source in any way and only passes it to [glShaderSource](https://www.opengl.org/sdk/docs/man/html/glShaderSource.xhtml) so all functions defined in [OpenGLES Shading Language](https://www.khronos.org/files/opengles_shading_language.pdf) should be available.

**Comment by mateosss** [comment]
Yup, it was exactly that, thank you! . I was confused by the error `'floor' : no matching overloaded function found`
