### ISSUE TITLE
Exposing shader scripts in the filesystem?

### ISSUE THREAD

**Issue by stuartpb** [markusfisch/ShaderEditor#5]
This app looks pretty neat, but the lack of an easy way to manipulate and externally edit the shaders it uses is something of a dealbreaker. (On top of not being able to import a file I've typed up on my PC, it's kind of hard to develop shaders when I'm not even able to name them.)

What I'd like to see is an option somewhere in the UI to set a directory to use for shader files. This would let me do any fancy file importing / exporting / naming / versioning etc. using any file browser (along with other stuff like a Git client and/or an external text editor), while still making the elements of the UI such as the dropdown as usable as they currently are.

**Comment by markusfisch** [comment]
Thanks for the feedback. That's a good idea!

Put export/import of shaders to the file system on the list for the next release.

**Comment by stuartpb** [comment]
Oh geez, these are currently stored in the SQLite database, aren't they? :grimacing:

I'd rather have some kind of solution that just uses the filesystem directly - no import/export steps. I was kind of expecting that was halfway to the way it works now (based on the examples in res/raw/) - I guess it would take a fair bit more work to implement than I imagined.

**Comment by markusfisch** [comment]
Yes, shaders are stored in a SQLite database. But importing/exporting shaders to and from files shouldn't be too difficult.

**Comment by stuartpb** [comment]
That's true, and having import/export is better than nothing - but needing to manage duplicated, [non-DRY](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself) file copies of every shader to reap the benefits of having the shaders available as files (Dropbox/Drive/Syncthing syncing, Git versioning, file transfer, backup archives), as opposed to just having them *live* in the filesystem... it gives me pause.

**Comment by markusfisch** [comment]
Yes, I see. Having to manage duplicates is definitely something to avoid.

What about extending the database to (optionally) just point to a file path?

**Comment by stuartpb** [comment]
You mean still using the database to keep all the extra data (like thumbnails etc.) and just read the file contents / listings from a directory (which is stored with the rest of the top-level app settings like which shader is the wallpaper)? That's pretty much the solution I was thinking (except without the "optionally" part).

**Comment by markusfisch** [comment]
Yes, that's it. I think that could work. Will try.

**Comment by bobbysoon** [comment]
So, no implementation yet? I couldn't find the files. 
I like the specify filepath idea, or any computer-accessible path, and if it auto-reloaded when file modified, by notepad++ on connected computer for example, that would be awesome :grinning:

**Comment by markusfisch** [comment]
Sorry, I know this issue is almost three years old and everything is still saved in a SQLite Database within the private app directory :( But I think the import and export, actually the sharing, of shaders (and textures) is too cumbersome in general and I'd like to address that first. Maybe it will solve this issue too.

**Comment by bobbysoon** [comment]
Looking forward to it. Great app, regardless :+1:
