### ISSUE TITLE
Rotation values

### ISSUE THREAD

**Issue by stefnotch** [markusfisch/ShaderEditor#51]
The explanation of the rotation values (vec3 rotation) is rather unhelpful. Also, I'm not sure if they work correctly on my device.

After some quick testing, it seems that:
1) They are angles. 
2) If you want them to be in a sensible range, (e.g. 0 to 1) you have to use mod(). (Because those angles apparently range from -infinity to +infinity)
3) y = tilting my device right and left
4) z = turning around
5) x is a weirdo. I have no clue what it represents. (It might seem like it should be: tilting my device forwards and backwards, but that doesn't seem to be the case?)

My code:
This code works perfectly fine with y and z.
mod(rotation.x / 6.2831, 1.0)

P.S. Awesome app! :)

**Comment by markusfisch** [comment]
Sorry for the late answer; you're right, the description is too vague and probably even misleading.

`rotation` is the rate of rotation in rad/s around a device's x, y, and z axis integrated over time to calculate a rotation describing the change of angles over a timestep.

It's the [processed output](https://developer.android.com/guide/topics/sensors/sensors_motion.html#sensors-motion-gyro) of the [gyroscope sensor](https://developer.android.com/guide/topics/sensors/sensors_overview.html#sensors-intro). Current implementation is in [hardware/GyroscopeListener.java](https://github.com/markusfisch/ShaderEditor/blob/master/app/src/main/java/de/markusfisch/android/shadereditor/hardware/GyroscopeListener.java).

Please check out the [Sensor Coordinate System](https://developer.android.com/guide/topics/sensors/sensors_overview.html#sensors-coords) to see how x, y and z are mapped to the device.

That said, looking at the code, I *think* I may have got concatenating the rotation matrix a bit wrong, but I need further tests to be sure.

**Comment by stefnotch** [comment]
Seems to work perfectly now. :)

**Comment by markusfisch** [comment]
Wow you're fast :) Was just about to write that you may check it out in the [Beta](https://play.google.com/apps/testing/de.markusfisch.android.shadereditor) if you like.

Also I added a new uniform `orientation` that gives azimuth, pitch and roll (see <a href="https://developer.android.com/reference/android/hardware/SensorManager.html#getOrientation(float[], float[])">documentation</a> for details).
