### ISSUE TITLE
App/service is always running in the background

### ISSUE THREAD

**Issue by waterdaan** [markusfisch/ShaderEditor#52]
Go to android settings > developer options > running services; there's a service running even though I'm not using a wallpaper and haven't used the app in quite a while

**Comment by markusfisch** [comment]
That's just the [WallpaperService](https://developer.android.com/reference/android/service/wallpaper/WallpaperService.html) being available but idle. Android (potentially) keeps it in memory to make it available without having to reload and recreate the service what would take more resources (battery), than simply keeping it in memory.

Please have a look at [this](https://www.wired.com/2016/03/closing-apps-save-battery-makes-things-worse/), [this](https://www.quora.com/Should-I-use-task-killer-apps) or [this](http://lifehacker.com/5650894/android-task-killers-explained-what-they-do-and-why-you-shouldnt-use-them) for a more elaborate explanation on the matter.

If you're concerned an app might use too much battery (pretty much the only resource we users do care about, right?), please look into Settings -> Battery. There you'll find what apps take the most energy. If you haven't used Shader Editor extensively just now, it shouldn't be among them.

**Comment by waterdaan** [comment]
Thanks for your quick response

I agree with you about background processes, however....
[https://developer.android.com/guide/components/services.html](https://developer.android.com/guide/components/services.html)

> onStartCommand()
The system invokes this method by calling startService() when another component (such as an activity) requests that the service be started. When this method executes, the service is started and can run in the background indefinitely. If you implement this, it is your responsibility to stop the service when its work is complete by calling stopSelf() or stopService(). 



I don't know anything about wallpapers, but I imagine that the app knows when I'm using  its wallpaper or not. So you could enable/disable the BatteryLevelReceiver (that starts the ShaderWallpaperService) accordingly.
[http://stackoverflow.com/questions/24266039/programatically-enable-disable-broadcastreceiver](http://stackoverflow.com/questions/24266039/programatically-enable-disable-broadcastreceiver)

Thanks for your time
Amazing app, by the way!!

**Comment by markusfisch** [comment]
You were right, there was a problem! After some investigation I found out, that the service lived much longer than it should. That's fixed now. And I've also added that explicit stopSelf() when the wallpaper is destroyed (although it does not seem to make a difference anymore).

Version 2.5.2 is submitted on Play and should be live in the next few hours.

Thank you for looking closely! The app's amazing because of people like you.

**Comment by waterdaan** [comment]
You're too nice

It turns out I misinformed you, [WallpaperService](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/service/wallpaper/WallpaperService.java) is a bound service, so you don't have to call stopSelf(). Sorry

I've just made my first pull request, hope it's ok

**Comment by markusfisch** [comment]
Ah, yes, of course, I totally forgot that :) I just (manually) merged your pull request. Thanks a lot!
