### ISSUE TITLE
Texture loading doesn't work on Xiaomi phones

### ISSUE THREAD

**Issue by Lolmarty** [markusfisch/ShaderEditor#56]
After adding the default noise texture via 'Add uniform/texture' menu and filling out the rest of the method that tiles the noise texture all over the screen, the app renders a black shader instead of repeating the texture. I'm not well familiarized with OpenGL, so apologies, if I'm doing something wrong. This issue has been reproduced on Xiaomi Mi4c and Xiaomi Redmi 4 Prime/Pro. The code that does the tiling itself is below.
```
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform vec2 resolution;
uniform sampler2D noise;

void main( void )
{
vec2 tempPos= vec2(mod(gl_FragCoord.x,256.),mod(gl_FragCoord.y,256.));
vec3 uv = texture2D(noise, tempPos).rgb;

gl_FragColor = vec4( uv, 1.0 );
}
```

**Comment by fekga** [comment]
The variable `gl_FragCoord` has the coordinates of your screen in pixels, it means that the integer part of them will be usable (e.g 1920*1080 -> vec2(1920.0,1080.0))
Dividing it by your resolution will return value between 0.0 and 1.0. This normalized value can be used to sample the texture.
As you want to use the texture as sampling, use it's resolution to divide the coordinates:

```
uniform sampler2D noise;

void main( void )
{
    vec2 noiseResolution = vec2(256.0); // == vec2(256.0,256.0)
    vec2 st = gl_FragCoord.xy/noiseResolution; // normalized to [vec2(0.0),vec2(1.0)]
    vec3 color = texture2D(noise, st).rgb; // sample the texture

    gl_FragColor = vec4( color, 1.0 ); // set the final fragment's color
}
```

ShaderEditor is set up to repeat your texture, so you actually don't have to use the modulo function. This isn't a GLSL setting, it's an OpenGL setting. It would be nice to have different repeating/clamping settings, but in your case it will work as you want it.

PS: welcome to OpenGL and GLSL :)

**Comment by Lolmarty** [comment]
Thank you!

**Comment by markusfisch** [comment]
The latest version from just yesterday (2.6.0) also allows different texture parameters for each uniform sampler* statement. Simply put something like "///min:n;mag:l;s:c;t:c" after the statement to set parameters for glTexParameteri():

```glsl
uniform sampler2D backbuffer; ///min:n;mag:n;s:c;t:c
```

Where `min` is [GL_TEXTURE_MIN_FILTER](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml), `mag` is [GL_TEXTURE_MAG_FILTER](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml) and `s` and `t` is [GL_TEXTURE_WRAP_S](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml) and [GL_TEXTURE_WRAP_T](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml). You may skip any parameter.

Also there's a new widget to choose from the possible values when a new texture is added or inserted into the source.

**Comment by fekga** [comment]
Wow, nice!
It seems that CLAMP_TO_BORDER is not included, why is that?

**Comment by markusfisch** [comment]
Yes, that's the reason. It comes with [GLES32](https://developer.android.com/reference/android/opengl/GLES32.html#GL_CLAMP_TO_BORDER) in API level 24 so - in theory - it should be possible to add it for devices >= 24. But I think that should be part of supporting GLES32 altogether.

http://docs.gl is really useful! Thanks for sharing!

**Comment by fekga** [comment]
The docs.gl page could be included in the Readme to help old and new GLSL users ;)

**Comment by markusfisch** [comment]
Good idea, added in https://github.com/markusfisch/ShaderEditor/commit/16f0d4e295c6f8a019894e2c9d3e40ff55c3dfa5
