### ISSUE TITLE
Uniform time is not working when live.

### ISSUE THREAD

**Issue by Jarann** [markusfisch/ShaderEditor#59]
I was trying to create a pulse effect by using time with sin. This worked fine in the editor but when I tried to use it as a wallpaper, it froze time and kept the color at one value. Is this something wrong with the app or my galaxy s6?

**Comment by fekga** [comment]
I think you might have turned on the battery saving option.

**Comment by Jarann** [comment]
It suddenly worked after I posted this. So yeah...
