### ISSUE TITLE
Docs / examples for all exposed inputs

### ISSUE THREAD

**Issue by stuartpb** [markusfisch/ShaderEditor#6]
It would be useful if there were either documentation of the names and values of the inputs to shaders in the README, or a shader/shaders that used them out-of-the-box (or, ideally, both).

I guess they're implemented somewhere around [here](https://github.com/markusfisch/ShaderEditor/blob/master/src/de/markusfisch/android/shadereditor/ShaderRenderer.java#L327-350)?

This is an awesome app, BTW - basically an open-source Android alternative to [Shaderific][]. Found it through F-Droid. I'm becoming obsessed with creating shader-based wallpapers for my new Nexus 6.

[Shaderific]: http://www.shaderific.com/

**Comment by stuartpb** [comment]
Documentation in-app would be awesome, too, like https://www.shadertoy.com/new's "Shader Inputs" accordion.

**Comment by markusfisch** [comment]
Well, there's the "new shader" in [res/raw/new_shader.xml](https://github.com/markusfisch/ShaderEditor/blob/master/res/raw/new_shader.txt) that enlists all options. But that's very basic, of course.

There should be a better documentation.

And I thought about Shadertoy compatible symbols too. I think there's even a Web API or something so it may be possible to import shaders directly from there. It's on my list!

**Comment by markusfisch** [comment]
https://github.com/markusfisch/ShaderEditor/commit/3ba88ccff7224323c052baef0c18502427e98d68 introduces an annotated listing of the available uniform's. Picking a list entry inserts the corresponding uniform in the shader.
