### ISSUE TITLE
Default Backbuffer Image

### ISSUE THREAD

**Issue by stefnotch** [markusfisch/ShaderEditor#61]
Currently: At the beginning, the backbuffer is black, which doesn't make sense for every shader. (You can work around this with an if statement in the shader...)
Suggestion: Add the ability to set the backbuffer to some image.

This would be great for procedural effects & other effects that rely a lot on the previous state.

**Comment by markusfisch** [comment]
That's a really good idea! Actually, that would come in handy for a shader of mine ...

Started to think about how to implement this.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/ShaderEditor/commit/d0d609e030d1c5c160106811b73ed336327e1038, will be in the next release.
