### ISSUE TITLE
Adaptive Icons

### ISSUE THREAD

**Issue by yvan-sraka** [markusfisch/ShaderEditor#63]
Hello,

What do you think about using the new [Adaptive Icons](https://developer.android.com/preview/features/adaptive-icons.html) feature of Android O?

It would be really nice to see them implemented in ShaderEditor! Can I help :wink:?

Thank you very much,

**Comment by markusfisch** [comment]
Hi, actually I've tried to add this yesterday (already made foreground and background assets) but then I saw it requires minSDK 26 😬

So the only sane way would be to create multiple APKs for different API levels but I'm not sure it's quite worth the hassle.

**Comment by yvan-sraka** [comment]
You're right, but we can also, without upgrading the API level of the application, use adaptive icon guidelines to create a standalone icon that provides both design consistency and backward compatibility!

**Comment by c-e-p-x-u-o** [comment]
Yes, please add support for icon shape

**Comment by markusfisch** [comment]
Added in https://github.com/markusfisch/ShaderEditor/commit/aceabe4ca7ce5181773dda377c3a1ddc90f60868 and https://github.com/markusfisch/ShaderEditor/commit/25b9996d2ad2788199465d5529bad8c91b212e4f
