### ISSUE TITLE
Adding a camera uniform breaks specifying GLSL version

### ISSUE THREAD

**Issue by Tynach** [markusfisch/ShaderEditor#74]
Specifically, I get this error when I try adding `uniform samplerExternalOES cameraBack;` near the top (but obviously under `#version 100`):

> ":    GLSL error: #version must occur  
> before any other statement in the program

Yes, the quotation mark and colon are part of the error. Here is a minimal shader that triggers this bug (almost literally the default camera shader, but with `#version 100` added to the top):

```glsl
#version 100

uniform vec2 resolution;
uniform vec2 cameraAddent;
uniform mat2 cameraOrientation;
uniform samplerExternalOES cameraBack;

void main(void) {
	vec2 uv = gl_FragCoord.xy / resolution.xy;
	vec2 st = cameraAddent + uv * cameraOrientation;

	gl_FragColor = vec4(texture2D(cameraBack, st).rgb, 1.0);
}
```

Commenting out the first line lets it work just fine.

**Comment by markusfisch** [comment]
Ah, yes, this is my fault 🙈`sampleExternalOES` requires the preprocessor directive `#extension GL_OES_EGL_image_external : require` which is silently [inserted](https://github.com/markusfisch/ShaderEditor/blob/master/app/src/main/java/de/markusfisch/android/shadereditor/opengl/ShaderRenderer.java#L1288) at the top of the shader when there is a `sampleExternalOES` uniform statement. Of course, `#version` must be the very first preprocessor directive, so I'll fix this as soon as possible.

**Comment by Tynach** [comment]
No worries, figured it was something like this! I tried looking through the code, but didn't quite find where it was happening!

Thank you for the quick replies for both of my bug reports, by the way :)

**Comment by markusfisch** [comment]
Thanks for submitting bugs! :)

Fixed in https://github.com/markusfisch/ShaderEditor/commit/303e247bfd9b2492bc6cfac8d71ad3835a6ef203

Put it the [Beta](https://play.google.com/apps/testing/de.markusfisch.android.shadereditor) on Play, should become available in the next few minutes.
