### ISSUE TITLE
Syntax highlight switch request

### ISSUE THREAD

**Issue by fekga** [markusfisch/ShaderEditor#83]
I'm doing some raymarching on my phone with the editor and the shader gets really big (couple houndred lines). As I try to scroll through it it gets really slow and choppy. This is a known issue but maybe by turning syntax highlight off it would speed it up by a lot?

**Comment by markusfisch** [comment]
Yes, turning syntax highlighting off would speed it up - but editing large texts can still be quite slow I'm afraid. Anyway, I will add this option in the settings so you can use that for large texts.

Unfortunately, Android's EditText just wasn't meant to deal with large texts. This app is desperately in need of a better editor ...

**Comment by fekga** [comment]
That would be a huge thing! 
Yeah it really needs a better editor, hope you or some contributer can do this sometime :)

**Comment by markusfisch** [comment]
Added in https://github.com/markusfisch/ShaderEditor/commit/62751083199600a3a2fcec7fc767af519f2bb82b

I just released a new beta 2.12.0 with this preference. Should become available within the next hour or so. You can get the beta version here:

https://play.google.com/apps/testing/de.markusfisch.android.shadereditor
