### ISSUE TITLE
File location of saved shaders

### ISSUE THREAD

**Issue by SergeantSarcasm** [markusfisch/ShaderEditor#84]
This may have already been stated somewhere but I have yet to find it, any way I can find where exactly the shader files are saved? It would make things a lot easier if I could do my work from my PC with an actual keyboard but I'm not sure if that is actually possible. Any advice would help.

**Comment by markusfisch** [comment]
Yes, there's already an open issue about this topic: https://github.com/markusfisch/ShaderEditor/issues/5

At the moment shaders are not saved in separate files but in a SQLite database within the app's private directory because of meta data like the desired resolution, thumbnail and so on.
