### ISSUE TITLE
Multitouch

### ISSUE THREAD

**Issue by stuartpb** [markusfisch/ShaderEditor#9]
It would be cool if `touch` were changed to be an array of (up to 10)? touches on-screen, for recognizing multi-touch. Each touch could be a `vec2`, with touches that aren't down set to `(-1, -1)`.

(I had some crazier ideas about representing touch state, including the `vec3` pattern Shadertoy uses for mouse input where `z` acts as an up/down boolean, but ultimately the best ideas I had were just awkward gestures at an incomplete persistence model.)

**Comment by stuartpb** [comment]
That said, one sensible value for a `z` attribute would be that touch's [touch size](http://developer.android.com/reference/android/view/MotionEvent.html#AXIS_TOUCH_MAJOR).

**Comment by markusfisch** [comment]
Cool idea! I was already planing to support multitouch with the next release but haven't thought about the touch size in z. Will come!

**Comment by markusfisch** [comment]
Landed in master.
