### ISSUE TITLE
When using a constant array, the app exits by accident without any error shown.

### ISSUE THREAD

**Issue by Ovizro** [markusfisch/ShaderEditor#99]
A const array can make the app crash. But if I delete the prefix "const", it does work well.

**Comment by markusfisch** [comment]
Sorry for this 😬  But this is a crash happens in the GLSL library of your device, unfortunately. There is nothing the app could do about it.

**Comment by Ovizro** [comment]
Thanks. Maybe I just need a new phone. :)
